### ISSUE TITLE
사용자의 가족 정보 불러오기

### ISSUE THREAD

**Issue by sunseo18** [TeamZOOC/ZOOC-SERVER#22]
## 📌 Feature Issue
- GET /family api 구현

## 📝 To-do

- [x] controller 코드 작성
- [x] response 메시지 생성
- [x] 유저 정보 조회
