### ISSUE TITLE
[GET] alarm/list 알림 리스트 조회하기

### ISSUE THREAD

**Issue by sunseo18** [TeamZOOC/ZOOC-SERVER#46]
## 📌 Feature Issue
- 알림 리스트 조회하기 api

## 📝 To-do

- [x] 서비스 코드 구현
- [x] 컨트롤러 코드 구현
- [x] 라우터 코드 구현
